github.com:
    users:
        darkace1998:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: darkace1998
