package dreadgameconfig

type WeaponStats struct {
	SlotType                          string  `json:"m_slotType"`
	Class                             string  `json:"m_class"`
	DamageHigh                        int32   `json:"m_damageHigh"`
	DamageHighRange                   int32   `json:"m_damageHighRange"`
	DamageMedium                      int32   `json:"m_damageMedium"`
	DamageMediumRange                 int32   `json:"m_damageMediumRange"`
	DamageLow                         int32   `json:"m_damageLow"`
	AmplifiedDamageHigh               int32   `json:"m_amplifiedDamageHigh"`
	AmplifiedDamageMedium             int32   `json:"m_amplifiedDamageMedium"`
	AmplifiedDamageLow                int32   `json:"m_amplifiedDamageLow"`
	MaxRange                          int32   `json:"m_maxRange"`
	DamageRadius                      int32   `json:"m_damageRadius"`
	IgnoreShields                     bool    `json:"m_ignoreShields"`
	FriendlyFire                      bool    `json:"m_friendlyFire"`
	ExactHitDetection                 bool    `json:"m_exactHitDetection"`
	InstigatorIgnoreTime              float64 `json:"m_instigatorIgnoreTime"`
	WeaponChargeUpTime                float64 `json:"m_weaponChargeUpTime"`
	WeaponCooldownTime                float64 `json:"m_weaponCooldownTime"`
	AmplifiedCoolDownMultiplierTime   float64 `json:"m_amplifiedCoolDownMultiplierTime"`
	AbilityDamage                     float64 `json:"m_abilityDamage"`
	InitialSpeed                      int32   `json:"m_initialSpeed"`
	MaxFlightSpeed                    int32   `json:"m_maxFlightSpeed"`
	GravityScale                      float64 `json:"m_gravityScale"`
	AmmoMagazinSize                   int32   `json:"m_ammoMagazinSize"`
	AmmoMagazinReloadTime             float64 `json:"m_ammoMagazinReloadTime"`
	AmplifiedAmmoMagazinReloadTime    float64 `json:"m_amplifiedAmmoMagazinReloadTime"`
	SpreadBaseValue                   float64 `json:"m_spreadBaseValue"`
	SpreadMaxValue                    float64 `json:"m_spreadMaxValue"`
	SpreadEase                        float64 `json:"m_spreadEase"`
	SpreadBonusAim                    float64 `json:"m_spreadBonusAim"`
	SpreadPenaltyMovement             float64 `json:"m_spreadPenaltyMovement"`
	SpreadPenaltyShooting             float64 `json:"m_spreadPenaltyShooting"`
	SpreadPenaltyDamageMultiplier     float64 `json:"m_spreadPenaltyDamageMultiplier"`
	ProximityDistance                 int32   `json:"m_proximityDistance"`
	ProximityAgainstCreeps            bool    `json:"m_proximityAgainstCreeps"`
	HighHealing                       int32   `json:"m_highHealing"`
	HighHealingRange                  int32   `json:"m_highHealingRange"`
	MediumHealing                     int32   `json:"m_mediumHealing"`
	MediumHealingRange                int32   `json:"m_mediumHealingRange"`
	LowHealing                        int32   `json:"m_lowHealing"`
	MaxHealingRange                   int32   `json:"m_maxHealingRange"`
	HitImpactForce                    int32   `json:"m_hitImpactForce"`
	FireRecoilForce                   int32   `json:"m_fireRecoilForce"`
	AmplifiedEnergyCost               float64 `json:"m_amplifiedEnergyCost"`
	HitzoneDamageMultiplier           float64 `json:"m_hitzoneDamageMultiplier"`
	HitzoneHitPenetrationDistance     float64 `json:"m_hitzoneHitPenetrationDistance"`
	PreciseAimingRange                int32   `json:"m_preciseAimingRange"`
}
