// Code generated by scripts/gen-mpquest-table.py; DO NOT EDIT.

package main

// mpQuestTable is the client's UYMPQuestsCollection, in its own order: the
// rows YA_GetDailyContractsData's ContractTable must carry.
var mpQuestTable = []mpQuestRow{
	{id: "YMPQ_CompleteMatches", path: "/Game/Generic/MPQuests/YMPQ_CompleteMatches.YMPQ_CompleteMatches", rank: 0},
	{id: "YMPQ_DestroyArtilleryCruiser", path: "/Game/Generic/MPQuests/YMPQ_DestroyArtilleryCruiser.YMPQ_DestroyArtilleryCruiser", rank: 0},
	{id: "YMPQ_DestroyCorvette", path: "/Game/Generic/MPQuests/YMPQ_DestroyCorvette.YMPQ_DestroyCorvette", rank: 0},
	{id: "YMPQ_DestroyDestroyer", path: "/Game/Generic/MPQuests/YMPQ_DestroyDestroyer.YMPQ_DestroyDestroyer", rank: 0},
	{id: "YMPQ_DestroyDreadnought", path: "/Game/Generic/MPQuests/YMPQ_DestroyDreadnought.YMPQ_DestroyDreadnought", rank: 0},
	{id: "YMPQ_DestroyTacticalCruiser", path: "/Game/Generic/MPQuests/YMPQ_DestroyTacticalCruiser.YMPQ_DestroyTacticalCruiser", rank: 0},
	{id: "YMPQ_Kills", path: "/Game/Generic/MPQuests/YMPQ_Kills.YMPQ_Kills", rank: 0},
	{id: "YMPQ_KillsArtilleryCruiser", path: "/Game/Generic/MPQuests/YMPQ_KillsArtilleryCruiser.YMPQ_KillsArtilleryCruiser", rank: 10},
	{id: "YMPQ_KillsCorvette", path: "/Game/Generic/MPQuests/YMPQ_KillsCorvette.YMPQ_KillsCorvette", rank: 10},
	{id: "YMPQ_KillsDestroyer", path: "/Game/Generic/MPQuests/YMPQ_KillsDestroyer.YMPQ_KillsDestroyer", rank: 10},
	{id: "YMPQ_KillsDreadnought", path: "/Game/Generic/MPQuests/YMPQ_KillsDreadnought.YMPQ_KillsDreadnought", rank: 10},
	{id: "YMPQ_KillsTacticalCruiser", path: "/Game/Generic/MPQuests/YMPQ_KillsTacticalCruiser.YMPQ_KillsTacticalCruiser", rank: 10},
	{id: "YMPQ_ModuleKills", path: "/Game/Generic/MPQuests/YMPQ_ModuleKills.YMPQ_ModuleKills", rank: 0},
	{id: "YMPQ_ModuleKillsTacticalCruiser", path: "/Game/Generic/MPQuests/YMPQ_ModuleKillsTacticalCruiser.YMPQ_ModuleKillsTacticalCruiser", rank: 20},
	{id: "YMPQ_ModuleKillsArtilleryCruiser", path: "/Game/Generic/MPQuests/YMPQ_ModuleKillsArtilleryCruiser.YMPQ_ModuleKillsArtilleryCruiser", rank: 20},
	{id: "YMPQ_ModuleKillsDestroyer", path: "/Game/Generic/MPQuests/YMPQ_ModuleKillsDestroyer.YMPQ_ModuleKillsDestroyer", rank: 20},
	{id: "YMPQ_ModuleKillsDreadnought", path: "/Game/Generic/MPQuests/YMPQ_ModuleKillsDreadnought.YMPQ_ModuleKillsDreadnought", rank: 20},
	{id: "YMPQ_ModuleKillsCorvette", path: "/Game/Generic/MPQuests/YMPQ_ModuleKillsCorvette.YMPQ_ModuleKillsCorvette", rank: 20},
	{id: "YMPQ_WinMatches", path: "/Game/Generic/MPQuests/YMPQ_WinMatches.YMPQ_WinMatches", rank: 0},
	{id: "YMPQ_CompleteMatchesONS", path: "/Game/Generic/MPQuests/YMPQ_CompleteMatchesONS.YMPQ_CompleteMatchesONS", rank: 0},
	{id: "YMPQ_WinMatchesONS", path: "/Game/Generic/MPQuests/YMPQ_WinMatchesONS.YMPQ_WinMatchesONS", rank: 0},
	{id: "YMPG_MatchScoreONS", path: "/Game/Generic/MPQuests/YMPQ_MatchScoreONS.YMPQ_MatchScoreONS", rank: 0},
	{id: "YMPQ_WinMatchesTER", path: "/Game/Generic/MPQuests/YMPQ_WinMatchesTER.YMPQ_WinMatchesTER", rank: 0},
	{id: "YMPQ_CompleteMatchesTURBO", path: "/Game/Generic/MPQuests/YMPQ_CompleteMatchesTURBO.YMPQ_CompleteMatchesTURBO", rank: 0},
}

// From MPQuestCollection.m_dailyContractsConfig.
const mpQuestNumBaseContractSlots = 3
const mpQuestNumEliteContractSlots = 1

// mpQuestInitialContracts is m_dailyContractsConfig.m_initialContracts.
var mpQuestInitialContracts = []string{
	"YMPQ_CompleteMatches",
	"YMPQ_ModuleKills",
	"YMPQ_Kills",
	"YMPQ_WinMatches",
	"YMPQ_DestroyTacticalCruiser",
	"YMPQ_DestroyDestroyer",
	"YMPQ_DestroyArtilleryCruiser",
	"YMPQ_DestroyDreadnought",
	"YMPQ_DestroyCorvette",
}
