// Code generated by scripts/gen-mpquest-rules.py; DO NOT EDIT.

package main

// mpQuestRules is what each quest of the client's MPQuestCollection counts
// (data/mpquests/MPQuestRules.json). See daily_contracts.go.
var mpQuestRules = []mpQuestRule{
	{id: "YMPQ_CompleteMatches", kind: mpQuestPlayed, counts: [3]int32{2, 2, 2}, rewards: [3]int32{5000, 5000, 5000}, rank: 0, outcomes: []string{"win", "loss", "draw"}},
	{id: "YMPQ_DestroyArtilleryCruiser", kind: mpQuestKills, counts: [3]int32{4, 4, 4}, rewards: [3]int32{5000, 5000, 5000}, rank: 0, killed: []int32{3, 10, 11}},
	{id: "YMPQ_DestroyCorvette", kind: mpQuestKills, counts: [3]int32{4, 4, 4}, rewards: [3]int32{5000, 5000, 5000}, rank: 0, killed: []int32{2, 8, 9}},
	{id: "YMPQ_DestroyDestroyer", kind: mpQuestKills, counts: [3]int32{4, 4, 4}, rewards: [3]int32{5000, 5000, 5000}, rank: 0, killed: []int32{5, 14, 15}},
	{id: "YMPQ_DestroyDreadnought", kind: mpQuestKills, counts: [3]int32{4, 4, 4}, rewards: [3]int32{5000, 5000, 5000}, rank: 0, killed: []int32{1, 6, 7}},
	{id: "YMPQ_DestroyTacticalCruiser", kind: mpQuestKills, counts: [3]int32{4, 4, 4}, rewards: [3]int32{5000, 5000, 5000}, rank: 0, killed: []int32{4, 12, 13}},
	{id: "YMPQ_Kills", kind: mpQuestKills, counts: [3]int32{6, 6, 6}, rewards: [3]int32{5000, 5000, 5000}, rank: 0},
	{id: "YMPQ_KillsArtilleryCruiser", kind: mpQuestKills, counts: [3]int32{5, 5, 5}, rewards: [3]int32{5000, 5000, 5000}, rank: 10, killer: []int32{3, 10, 11}},
	{id: "YMPQ_KillsCorvette", kind: mpQuestKills, counts: [3]int32{5, 5, 5}, rewards: [3]int32{5000, 5000, 5000}, rank: 10, killer: []int32{2, 8, 9}},
	{id: "YMPQ_KillsDestroyer", kind: mpQuestKills, counts: [3]int32{5, 5, 5}, rewards: [3]int32{5000, 5000, 5000}, rank: 10, killer: []int32{5, 14, 15}},
	{id: "YMPQ_KillsDreadnought", kind: mpQuestKills, counts: [3]int32{5, 5, 5}, rewards: [3]int32{5000, 5000, 5000}, rank: 10, killer: []int32{1, 6, 7}},
	{id: "YMPQ_KillsTacticalCruiser", kind: mpQuestKills, counts: [3]int32{2, 2, 2}, rewards: [3]int32{5000, 5000, 5000}, rank: 10, killer: []int32{4, 12, 13}},
	{id: "YMPQ_ModuleKills", kind: mpQuestKills, counts: [3]int32{3, 3, 3}, rewards: [3]int32{5000, 5000, 5000}, rank: 0, abilityOnly: true},
	{id: "YMPQ_ModuleKillsTacticalCruiser", kind: mpQuestKills, counts: [3]int32{2, 2, 2}, rewards: [3]int32{5000, 5000, 5000}, rank: 20, killer: []int32{4, 12, 13}, abilityOnly: true},
	{id: "YMPQ_ModuleKillsArtilleryCruiser", kind: mpQuestKills, counts: [3]int32{3, 3, 3}, rewards: [3]int32{5000, 5000, 5000}, rank: 20, killer: []int32{3, 10, 11}, abilityOnly: true},
	{id: "YMPQ_ModuleKillsDestroyer", kind: mpQuestKills, counts: [3]int32{3, 3, 3}, rewards: [3]int32{5000, 5000, 5000}, rank: 20, killer: []int32{5, 14, 15}, abilityOnly: true},
	{id: "YMPQ_ModuleKillsDreadnought", kind: mpQuestKills, counts: [3]int32{3, 3, 3}, rewards: [3]int32{5000, 5000, 5000}, rank: 20, killer: []int32{1, 6, 7}, abilityOnly: true},
	{id: "YMPQ_ModuleKillsCorvette", kind: mpQuestKills, counts: [3]int32{3, 3, 3}, rewards: [3]int32{5000, 5000, 5000}, rank: 20, killer: []int32{2, 8, 9}, abilityOnly: true},
	{id: "YMPQ_WinMatches", kind: mpQuestPlayed, counts: defaultObjectiveCounts, rewards: [3]int32{5000, 5000, 5000}, rank: 0, outcomes: []string{"win"}},
	{id: "YMPQ_CompleteMatchesONS", kind: mpQuestPlayed, counts: [3]int32{2, 2, 2}, rewards: [3]int32{5000, 5000, 5000}, rank: 0, outcomes: []string{"win", "loss", "draw"}, modes: []string{"Onslaught"}},
	{id: "YMPQ_WinMatchesONS", kind: mpQuestPlayed, counts: defaultObjectiveCounts, rewards: [3]int32{5000, 5000, 5000}, rank: 0, outcomes: []string{"win"}, modes: []string{"Onslaught"}},
	{id: "YMPG_MatchScoreONS", kind: mpQuestScore, counts: [3]int32{500, 500, 500}, rewards: [3]int32{5000, 5000, 5000}, rank: 0, modes: []string{"Onslaught"}},
	{id: "YMPQ_WinMatchesTER", kind: mpQuestPlayed, counts: defaultObjectiveCounts, rewards: [3]int32{5000, 5000, 5000}, rank: 0, outcomes: []string{"win"}, modes: []string{"TER"}},
	{id: "YMPQ_CompleteMatchesTURBO", kind: mpQuestPlayed, counts: [3]int32{2, 2, 2}, rewards: [3]int32{10000, 10000, 10000}, rank: 0, outcomes: []string{"win", "loss", "draw"}, modes: []string{"TurboTDM"}},
}
