#!/usr/bin/env python3
"""Generate mmogbrain/mpquest_rules_gen.go: what each daily contract counts.

Input: data/mpquests/MPQuestRules.json -- the class-default properties of the
24 quests in MPQuestCollection (DreadGame/Content/Generic/MPQuests/YMPQ_*.uasset),
enum values by name, read from the cooked assets on 2026-10-09:

  kind                     native parent: YMPQuest_GamePlayed (matches played),
                           YMPQuest_PlayerKills (kills), YMPQuest_EndOfMatchScore
  m_targetValues.m_objectiveCounts   target per difficulty (the entry's "dif")
  m_FPReward               reward per difficulty -- paid in credits (game text:
                           "You can earn Credits by playing matches and
                           completing contracts")
  m_requiredRank           captain rank needed to be offered the quest
  m_outcomeTypesFilter     EYMatchOutcome values that count
  m_battlesTypeFilter      game modes that count (EYGameModeType)
  m_killedShipClasses      classes of the destroyed ship that count
  m_killerClassFilter      classes the player must be flying
  m_onlyKillsWithAbilities only module kills count

A quest that leaves m_targetValues at the native default (the three Win quests)
gets defaultObjectiveCount -- GUESS, see the generated file.

Usage: python3 scripts/gen-mpquest-rules.py
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RULES = os.path.join(ROOT, "data/mpquests/MPQuestRules.json")
OUTPUT = os.path.join(ROOT, "mmogbrain/mpquest_rules_gen.go")

CLASSES = {
    "YSC_DREADNOUGHT_LIGHT": 1, "YSC_SCOUT_LIGHT": 2, "YSC_SNIPER_LIGHT": 3, "YSC_SUPPORT_LIGHT": 4,
    "YSC_ASSAULT_LIGHT": 5, "YSC_DREADNOUGHT_MEDIUM": 6, "YSC_DREADNOUGHT_HEAVY": 7, "YSC_SCOUT_MEDIUM": 8,
    "YSC_SCOUT_HEAVY": 9, "YSC_SNIPER_MEDIUM": 10, "YSC_SNIPER_HEAVY": 11, "YSC_SUPPORT_MEDIUM": 12,
    "YSC_SUPPORT_HEAVY": 13, "YSC_ASSAULT_MEDIUM": 14, "YSC_ASSAULT_HEAVY": 15,
}
# EYGameModeType -> the game_mode names the matchmaker records.
MODES = {"YGMT_TER": "TER", "YGMT_TURBO_TDM": "TurboTDM", "YGMT_INVASION": "Onslaught", "YGMT_TDM": "TDM"}
OUTCOMES = {"EYMatchOutcome::YBMR_WIN": "win", "EYMatchOutcome::YBMR_LOSE": "loss", "EYMatchOutcome::YBMR_TIE": "draw"}
KINDS = {"YMPQuest_GamePlayed": "mpQuestPlayed", "YMPQuest_PlayerKills": "mpQuestKills",
         "YMPQuest_EndOfMatchScore": "mpQuestScore"}


def go_list(items, fmt):
    return "[]" + fmt + "{" + ", ".join(str(i) if fmt != "string" else json.dumps(i) for i in items) + "}"


def main():
    rows = json.load(open(RULES, encoding="utf-8"))
    lines = []
    for r in rows:
        counts = (r.get("m_targetValues") or {}).get("m_objectiveCounts")
        counts = "[3]int32{%s}" % ", ".join(map(str, counts)) if counts else "defaultObjectiveCounts"
        rewards = r.get("m_FPReward") or [0, 0, 0]
        fields = [
            "id: %s" % json.dumps(r["id"]),
            "kind: %s" % KINDS[r["kind"]],
            "counts: %s" % counts,
            "rewards: [3]int32{%s}" % ", ".join(map(str, rewards)),
            "rank: %d" % int(r.get("m_requiredRank") or 0),
        ]
        if r.get("m_outcomeTypesFilter"):
            fields.append("outcomes: " + go_list([OUTCOMES[o] for o in r["m_outcomeTypesFilter"]], "string"))
        if r.get("m_battlesTypeFilter"):
            fields.append("modes: " + go_list([MODES[m] for m in r["m_battlesTypeFilter"]], "string"))
        killed = r.get("m_killedShipClasses") or []
        if killed and len(set(killed)) < len(CLASSES):
            fields.append("killed: " + go_list(sorted(CLASSES[c] for c in set(killed)), "int32"))
        if r.get("m_killerClassFilter"):
            fields.append("killer: " + go_list(sorted(CLASSES[c] for c in set(r["m_killerClassFilter"])), "int32"))
        if r.get("m_onlyKillsWithAbilities"):
            fields.append("abilityOnly: true")
        lines.append("\t{" + ", ".join(fields) + "},")
    with open(OUTPUT, "w", encoding="utf-8") as out:
        out.write("// Code generated by scripts/gen-mpquest-rules.py; DO NOT EDIT.\n\npackage main\n\n")
        out.write("// mpQuestRules is what each quest of the client's MPQuestCollection counts\n")
        out.write("// (data/mpquests/MPQuestRules.json). See daily_contracts.go.\n")
        out.write("var mpQuestRules = []mpQuestRule{\n" + "\n".join(lines) + "\n}\n")


if __name__ == "__main__":
    main()
