#!/usr/bin/env python3
"""Generate mmogbrain/mpquest_table_gen.go from the client's own quest assets.

The YA_GetDailyContractsData reply must carry "ContractTable": one row per
quest the client's UYMPQuestsCollection knows (verified 2026-09-25, parser
0x2A6B7F0 / row parser 0x2A69840). The original mmogbrain got this table as an
export of that same collection (DefaultScoring.ini: YMPQuestsCollection
m_mmogbrainExportPath = .../mmogbrain/instances/dreadnought/QuestsTable.cfg),
so it is rebuilt here from the cooked assets instead of being authored:

  data/mpquests/MPQuestCollection_cooked.jsonl
      bpdump --json DreadGame/Content/Generic/MPQuests/MPQuestCollection.uasset
  data/mpquests/MPQuests_cooked.jsonl
      bpdump --loadouts DreadGame/Content/Generic/MPQuests "YMPQ_*.uasset"

Row Id is each quest's own m_id, NOT its asset name: the client looks a row up
by comparing it with the quest CDO's m_id (0x3FBE90), and one asset's m_id is
misspelt ("YMPG_MatchScoreONS" in YMPQ_MatchScoreONS). Sending the asset name
would silently drop that quest.

Usage: python3 scripts/gen-mpquest-table.py
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COLLECTION = os.path.join(ROOT, "data/mpquests/MPQuestCollection_cooked.jsonl")
QUESTS = os.path.join(ROOT, "data/mpquests/MPQuests_cooked.jsonl")
OUTPUT = os.path.join(ROOT, "mmogbrain/mpquest_table_gen.go")


def load_quests():
    out = {}
    with open(QUESTS, encoding="utf-8") as handle:
        for line in handle:
            row = json.loads(line)
            export = row.get("export", "")
            if export.startswith("Default__") and export.endswith("_C"):
                out[export[len("Default__"):-2]] = row
    return out


def main():
    with open(COLLECTION, encoding="utf-8") as handle:
        collection = json.loads(handle.readline())
    quests = load_quests()
    config = collection["m_dailyContractsConfig"]

    rows = []
    for path in collection["m_questsAssetDefinition"]:
        asset = path.rsplit(".", 1)[1]
        quest = quests.get(asset)
        if quest is None or not quest.get("m_id"):
            raise SystemExit(f"{asset}: listed by the collection but not in {QUESTS}")
        rows.append((quest["m_id"], path, int(quest.get("m_requiredRank") or 0)))

    known = {r[0].lower() for r in rows} | {a.lower() for a in quests}
    for initial in config["m_initialContracts"]:
        if initial.lower() not in known:
            raise SystemExit(f"initial contract {initial} is not a known quest")

    lines = [
        "// Code generated by scripts/gen-mpquest-table.py; DO NOT EDIT.",
        "",
        "package main",
        "",
        "// mpQuestTable is the client's UYMPQuestsCollection, in its own order: the",
        "// rows YA_GetDailyContractsData's ContractTable must carry.",
        "var mpQuestTable = []mpQuestRow{",
    ]
    for quest_id, path, rank in rows:
        lines.append(f"\t{{id: {json.dumps(quest_id)}, path: {json.dumps(path)}, rank: {rank}}},")
    lines += [
        "}",
        "",
        "// From MPQuestCollection.m_dailyContractsConfig.",
        f"const mpQuestNumBaseContractSlots = {int(config['m_numBaseContractSlots'])}",
        f"const mpQuestNumEliteContractSlots = {int(config['m_numEliteContractSlots'])}",
        "",
        "// mpQuestInitialContracts is m_dailyContractsConfig.m_initialContracts.",
        "var mpQuestInitialContracts = []string{",
    ]
    for initial in config["m_initialContracts"]:
        lines.append(f"\t{json.dumps(initial)},")
    lines.append("}")

    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    print(f"wrote {OUTPUT}: {len(rows)} quests, {len(config['m_initialContracts'])} initial contracts")


if __name__ == "__main__":
    main()
