#!/usr/bin/env python3
"""Generate battle-server-mod/src/precast_paths.h: every precast loadout's asset
name -> its class path, from the cooked data (data/loadouts/PrecastLoadouts_cooked.jsonl).

The battle-server mod resolves a precast loadout by the name the game asks for
(FindLoadoutByID misses on "Default__<X>_C"). Only 54 of the 102 precasts live
in a Precast/T<n>/ folder that matches their name's tier -- the rest sit in
Special/ and elsewhere -- so the path cannot be derived; it is read from the
cooked asset list instead.

Usage: python3 scripts/gen-precast-paths.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data/loadouts/PrecastLoadouts_cooked.jsonl")
OUT = os.path.join(ROOT, "battle-server-mod/src/precast_paths.h")

entries = {}
for line in open(SRC):
    row = json.loads(line)
    f = row["file"]  # DreadGame/Content/<dir>/<X>.uasset
    assert f.startswith("DreadGame/Content/") and f.endswith(".uasset"), f
    pkg = "/Game/" + f[len("DreadGame/Content/"):-len(".uasset")]
    name = pkg.rsplit("/", 1)[1]
    assert row["export"] == f"Default__{name}_C", (row["export"], name)
    entries[name] = f"{pkg}.{name}_C"

with open(OUT, "w") as out:
    out.write("// GENERATED by scripts/gen-precast-paths.py from\n"
              "// data/loadouts/PrecastLoadouts_cooked.jsonl -- do not edit.\n"
              "// Precast loadout asset name -> class path for StaticLoadClass.\n"
              "#pragma once\n\n"
              "struct PrecastPath {\n  const char *name;\n  const wchar_t *path;\n};\n\n"
              "static const PrecastPath kAllPrecastPaths[] = {\n")
    for name in sorted(entries):
        out.write(f'    {{"{name}", L"{entries[name]}"}},\n')
    out.write("};\n\nstatic const int kAllPrecastCount =\n"
              "    (int)(sizeof(kAllPrecastPaths) / sizeof(kAllPrecastPaths[0]));\n")
print(f"wrote {len(entries)} precast paths to {OUT}")
